language: c

before_script:
  - git submodule update --init
  - ./buildrump.sh/buildrump.sh -s rumpsrc -o rumpobj -V MKSTATICLIB=no -q -j4

env:
  - LDFLAGS='-Lrump/lib -Wl,-Rrump/lib'
  - CPPFLAGS='-Irump/include'

script:
  - ./configure
  - make

notifications:
  irc:
    channels:
      - "chat.freenode.net#rumpkernel-builds"
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{me
ssage}'
    skip_join: true
    use_notice: true
  email:
    recipients:
      - rumpkernel-builds@lists.sourceforge.net
    on_success: always
    on_failure: always
